{ "prio" : 0, "err_code" : 13172, "source_line" : 2325, "source_file" : "sql_parse.cc", "function" : "shutdown", "msg" : "Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.23).", "time" : "2021-04-02T21:51:58.254498Z", "ts" : 1617400318254, "thread" : 11, "err_symbol" : "ER_SERVER_SHUTDOWN_INFO", "SQL_state" : "HY000", "subsystem" : "Server", "label" : "System" }
{ "prio" : 0, "err_code" : 10910, "source_line" : 2475, "source_file" : "mysqld.cc", "function" : "clean_up", "msg" : "/usr/sbin/mysqld: Shutdown complete (mysqld 8.0.23)  MySQL Community Server - GPL.", "time" : "2021-04-02T21:51:59.700938Z", "ts" : 1617400319700, "err_symbol" : "ER_SERVER_SHUTDOWN_COMPLETE", "SQL_state" : "HY000", "subsystem" : "Server", "label" : "System" }
{ "prio" : 0, "err_code" : 10116, "source_line" : 4642, "source_file" : "mysqld.cc", "function" : "init_common_variables", "msg" : "/usr/sbin/mysqld (mysqld 8.0.23) starting as process 1", "time" : "2021-04-02T21:52:00.544582Z", "ts" : 1617400320544, "err_symbol" : "ER_STARTING_AS", "SQL_state" : "HY000", "subsystem" : "Server", "buffered" : 1617400320544582, "label" : "System" }
{ "prio" : 0, "err_code" : 13576, "subsystem" : "InnoDB", "source_line" : 12296, "source_file" : "ha_innodb.cc", "function" : "innobase_ddse_dict_init", "msg" : "InnoDB initialization has started.", "time" : "2021-04-02T21:52:00.553186Z", "ts" : 1617400320553, "thread" : 1, "err_symbol" : "ER_IB_MSG_INNODB_START_INITIALIZE", "SQL_state" : "HY000", "buffered" : 1617400320553186, "label" : "System" }
{ "prio" : 0, "err_code" : 13577, "subsystem" : "InnoDB", "source_line" : 12433, "source_file" : "ha_innodb.cc", "function" : "innobase_ddse_dict_init", "msg" : "InnoDB initialization has ended.", "time" : "2021-04-02T21:52:00.790091Z", "ts" : 1617400320790, "thread" : 1, "err_symbol" : "ER_IB_MSG_INNODB_END_INITIALIZE", "SQL_state" : "HY000", "buffered" : 1617400320790091, "label" : "System" }
{ "prio" : 0, "err_code" : 11323, "component" : "mysqlx", "source_line" : 285, "source_file" : "socket_acceptors_task.cc", "function" : "show_startup_log", "msg" : "X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock", "time" : "2021-04-02T21:52:00.910314Z", "ts" : 1617400320910, "thread" : 0, "err_symbol" : "ER_XPLUGIN_LISTENER_STATUS_MSG", "SQL_state" : "HY000", "subsystem" : "Server", "buffered" : 1617400320910314, "label" : "System" }
{ "prio" : 2, "err_code" : 10068, "buffered" : 1617400321029405, "source_file" : "ssl_init_callback.cc", "function" : "operator()", "msg" : "CA certificate ca.pem is self signed.", "time" : "2021-04-02T21:52:01.029405Z", "ts" : 1617400321029, "err_symbol" : "ER_CA_SELF_SIGNED", "SQL_state" : "HY000", "subsystem" : "Server", "label" : "Warning" }
{ "prio" : 0, "err_code" : 13602, "source_line" : 88, "source_file" : "ssl_acceptor_context_operator.cc", "function" : "singleton_init", "msg" : "Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.", "time" : "2021-04-02T21:52:01.029775Z", "ts" : 1617400321029, "err_symbol" : "ER_TLS_CONFIGURED_FOR_CHANNEL", "SQL_state" : "HY000", "subsystem" : "Server", "buffered" : 1617400321029775, "label" : "System" }
{ "prio" : 2, "err_code" : 11810, "buffered" : 1617400321033731, "source_file" : "mysqld.cc", "function" : "create_pid_file", "msg" : "Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.", "time" : "2021-04-02T21:52:01.033731Z", "ts" : 1617400321033, "err_symbol" : "ER_PID_FILE_PRIV_DIRECTORY_INSECURE", "SQL_state" : "HY000", "subsystem" : "Server", "label" : "Warning" }
{ "log_type" : 1, "prio" : 0, "err_code" : 10931, "msg" : "/usr/sbin/mysqld: ready for connections. Version: '8.0.23'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.", "time" : "2021-04-02T21:52:01.056294Z", "ts" : 1617400321056, "err_symbol" : "ER_SERVER_STARTUP_MSG", "SQL_state" : "HY000", "subsystem" : "Server", "label" : "System" }
{ "prio" : 2, "err_code" : 10055, "subsystem" : "Server", "source_file" : "hostname_cache.cc", "function" : "ip_to_hostname", "msg" : "IP address '172.17.0.1' could not be resolved: Temporary failure in name resolution", "time" : "2021-04-02T21:52:24.054200Z", "ts" : 1617400344054, "thread" : 8, "err_symbol" : "ER_UNABLE_TO_RESOLVE_IP", "SQL_state" : "HY000", "label" : "Warning" }